
(package! org-roam)
(package! org-roam-server)
(package! org-roam-bibtex)
(package! org-ref)
(package! fish-mode)
(package! org-noter)
(package! bm)
(package! crux)
(package! el-patch)
;; (package! el-get)
(package! auto-compile)
(package! org-tanglesync)
(package! org-download)
(package! helm-bibtex)
(package! helm)
(package! ivy-bibtex)
(package! guix)
(package! stan-mode)
(package! academic-phrases)
(package! rainbow-blocks)
(package! company-org-roam)
(package! beancount :recipe (:host github :repo "cnsunyour/beancount.el"))
(package! artbollocks-mode)
(package! sicp)
(package! hyperbole)
(package! disable-mouse)
(package! eshell-z)
;; (package! exwm-mff)
;; (package! use-package-el-get)
(package! key-assist)
(package! backup-walker)
(package! cdlatex)
(package! literate-calc-mode)
(package! elcontext)
(package! prodigy)
(package! synosaurus)
(package! emacs-piper :recipe (:host gitlab :repo "howardabrams/emacs-piper"))
(package! vc-msg)
(package! git-messenger)
(package! feebleline)
(package! mini-modeline)
(package! unfill)
